// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhrYRusEbHuOjcebOQpcnLgdGq9p-PUbk',
    appId: '1:806024416381:web:2a8d73cb5b4ed6c847b514',
    messagingSenderId: '806024416381',
    projectId: 'realfeedback-af55c',
    authDomain: 'realfeedback-af55c.firebaseapp.com',
    storageBucket: 'realfeedback-af55c.firebasestorage.app',
    measurementId: 'G-DH0WQG2FHD'
    ,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhC5AKh1BxIJyN14ROc1EOQUx2rSRHbls',
    appId: '1:806024416381:android:7d70eaaca88a40bc47b514',
    messagingSenderId: '806024416381',
    projectId: 'realfeedback-af55c',
    storageBucket: 'realfeedback-af55c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhrYRusEbHuOjcebOQpcnLgdGq9p-PUbk',
    appId: '1:806024416381:web:af233d905b70b42047b514',
    messagingSenderId: '806024416381',
    projectId: 'realfeedback-af55c',
    authDomain: 'realfeedback-af55c.firebaseapp.com',
    storageBucket: 'realfeedback-af55c.firebasestorage.app',
    measurementId: 'G-FTR21NFTD7',
  );
}
